version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Update Dependencies
          command: npm install
      - run:
          name: Build the Angular App
          command: ng build
      - run:
          name: Start the Angular App
          command: ng serve
