version: 2
jobs:
  build:
    working_directory: ~/my-site
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
