version: 2
jobs:
  build:
    working_directory: ~/my-site
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - run:
          name: Update Dependencies
          command: npm install
      - run:
         name: Deploy Master to Firebase
         command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-job:
          requires:
            - build
          filters:
            branches:
              only: master
