version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Unit Tests
          command: ng test
      - run:
          name: Print the Current Time
          command: date
