version: 2
jobs:
  build:
    working_directory: ~/my-site
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - run:
          name: Update Dependencies
          command: npm install
